### ISSUE TITLE
How to disable logging

### ISSUE THREAD

**Issue by mbolesta** [Softlr/Selenium.WebDriver.Extensions#189]
How do I disable the jQuery logging? My test runner console is overrun when I use jQuery selectors:

`Entering: WebDriverExtensions.ExecuteScript({OpenQA.Selenium.PhantomJS.PhantomJSDriver}, "return jQuery('button:contains(Skip)').get();", {System.Object[]})
Leaving: WebDriverExtensions.ExecuteScript({OpenQA.Selenium.PhantomJS.PhantomJSDriver}, "return jQuery('button:contains(Skip)').get();", {System.Object[]}) : System.Collections.ObjectModel.ReadOnlyCollection`1[OpenQA.Selenium.IWebElement]
Entering: WebDriverExtensions.ExecuteScript({OpenQA.Selenium.PhantomJS.PhantomJSDriver}, "return (function(value) {
            'use strict';
            return typeof value === 'function';
        })(window.jQuery);", {System.Object[]})
Leaving: WebDriverExtensions.ExecuteScript({OpenQA.Selenium.PhantomJS.PhantomJSDriver}, "return (function(value) {
            'use strict';
            return typeof value === 'function';
        })(window.jQuery);", {System.Object[]}) : True`

**Comment by RaYell** [comment]
I believe this is the default behaviour of PhantomJS when arbitrary JS code is being executed. The library itself doesn't add any additional logging.
