### ISSUE TITLE
Postsharp is installed when you add nuget package

### ISSUE THREAD

**Issue by lukemcgregor** [Softlr/Selenium.WebDriver.Extensions#193]
Theres no reason it should get installed into consumers of the package.

I recommend removing it from the nuget references which you build with this package.

**Comment by RaYell** [comment]
The reason is, this library is using PostSharp (mostly [data contracts](http://doc.postsharp.net/contracts) but also [disposable](http://doc.postsharp.net/disposable)) so removing it from the dependencies would break it.

**Comment by tjrobinson** [comment]
@RaYell Could the nuget dependencies be changed to depend on `PostSharp.Patterns.Model.Redist` instead of `PostSharp.Patterns.Model`?

I don't know much about PostSharp and how it's licensed but the [PostSharp documentation](http://doc.postsharp.net/postsharp-components) says:

> The PostSharp License Agreement refers to run-time packages as redistributables. The license agreement allows for royalty-free redistribution of run-time packages, but stricter conditions apply to the redistribution of build-time packages.

I'm happy to create a PR if that would help?

**Comment by RaYell** [comment]
Sure, that sounds like a good idea.

**Comment by tjrobinson** [comment]
I was just about to create a PR but can see you've already done this, thanks!

**Comment by tjrobinson** [comment]
@RaYell Do you know when 3.2.0 will be pushed to nuget? Thanks.

**Comment by RaYell** [comment]
What do you need from 3.2? This issue was fixed in 3.1.1 which was releases a couple of months ago.

**Comment by tjrobinson** [comment]
Ah apologies, I updated to 3.1.1 but it didn't remove the unnecessary PostSharp packages.

**Comment by RaYell** [comment]
Yes, unfortunately I don't think there's a way of telling if the previous dependency was used only by that single package so they have to be removed manually.
