### ISSUE TITLE
CSP  Refused to load the script

### ISSUE THREAD

**Issue by lzmj** [Softlr/Selenium.WebDriver.Extensions#258]
If the website meta has CSP to prevent XSS attacks, jquery will not use it. 
The Console prints as follows:
`VM20:377 Refused to load the script 'https://code.jquery.com/jquery-latest.min.js' because it violates the following Content Security Policy directive: "script-src 'self' http://xxxx.com  blob: 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`
Can it be solved?

**Comment by RaYell** [comment]
I don't think there is anything on the lib's side to overwrite your security policy, it'd be a huge security issue if that was possible.

Two things that comes to mind are:
1. Add `code.jquery.com` to CSP allowed domains
```
script-src 'self' code.jquery.com;
```
2. Use jQuery from another domain that is on your CSP trusted list
3. Use a local version of jQuery served from the same domain as your other assets
